CC=gcc
DEBUG=#-g
DNDEBUG=-DNDEBUG
CFLAGS=-std=c99 -Wall -pedantic-errors -Werror $(DNDEBUG) $(DEBUG)
LDLIBS=-L. -lmtm

EXEC=mtm_game
ADT1=tournament
ADT2=judge
ADT3=chef
ADT4=dish
TEST_SUFFIX=_test

OBJS=mtm_game.o judge_preferences.o $(ADT1).o $(ADT2).o $(ADT3).o $(ADT4).o \
 common.o
TEST1=tests/$(ADT1)$(TEST_SUFFIX)
TEST2=tests/$(ADT2)$(TEST_SUFFIX)
TEST3=tests/$(ADT3)$(TEST_SUFFIX)
TEST4=tests/$(ADT4)$(TEST_SUFFIX)

#rules
$(EXEC) : $(OBJS)
tests : $(TEST1) $(TEST2) $(TEST3) $(TEST4)

$(TEST1) : $(TEST1).o $(ADT1).o $(ADT2).o $(ADT3).o $(ADT4).o common.o
$(TEST2) : $(TEST2).o $(ADT2).o $(ADT4).o common.o
$(TEST3) : $(TEST3).o $(ADT3).o $(ADT4).o common.o
$(TEST4) : $(TEST4).o $(ADT4).o common.o

#rules for obj files - generated by gcc -MM
chef.o: chef.c common.h priority_queue.h chef.h dish.h
common.o: common.c common.h
dish.o: dish.c dish.h common.h
mtm_game.o: mtm_game.c common.h mtm_wet3.h tournament.h chef.h dish.h \
	judge.h judge_preferences.h
judge.o: judge.c common.h chef.h dish.h set.h judge.h
judge_preferences.o: judge_preferences.c judge_preferences.h judge.h \
	dish.h
tournament.o: tournament.c set.h list.h common.h tournament.h chef.h \
	dish.h judge.h
tests/chef_test.o: tests/chef_test.c tests/test_utilities.h chef.h dish.h \
	common.h
tests/dish_test.o: tests/dish_test.c tests/test_utilities.h common.h dish.h
tests/judge_test.o: tests/judge_test.c tests/test_utilities.h judge.h dish.h \
	common.h

clean:
	rm -f $(OBJS) $(EXEC) $(TEST1).o $(TEST1) $(TEST2).o $(TEST2) \
	$(TEST3).o $(TEST3) $(TEST4).o $(TEST4)
