CC=gcc
DEBUG=#-g
DNDEBUG=-DNDEBUG
CFLAGS=-std=c99 -Wall -pedantic-errors -Werror $(DNDEBUG) $(DEBUG)
LDLIBS=-L. -lmtm

EXEC=mtm_game
ADT1=tournament
ADT2=judge
ADT3=chef
ADT4=dish
TEST_SUFFIX=_test

OBJS=$(ADT1).o $(ADT2).o $(ADT3).o $(ADT4).o
TEST1=$(ADT1)$(TEST_SUFFIX)
TEST2=$(ADT2)$(TEST_SUFFIX)
TEST3=$(ADT3)$(TEST_SUFFIX)
TEST4=$(ADT4)$(TEST_SUFFIX)

#rules
$(EXEC) : $(OBJS)
tests : $(TEST1) $(TEST2) $(TEST3) $(TEST4)
$(TEST1) : $(TEST1).o
$(TEST2) : $(TEST2).o
$(TEST3) : $(TEST3).o
$(TEST4) : $(TEST4).o

#rules for obj files - generated by gcc -MM
#todo...


clean:
rm -f $(OBJS) $(EXEC)
